name: Gradle CI

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch/tag name
        shell: bash
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "ref=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            ref="${GITHUB_REF#refs/heads/}"
            echo "ref=${ref////-}" >> $GITHUB_OUTPUT
          fi
        id: ref

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.ivy2/cache
          key: ${{ runner.os }}-maven-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: |
          if [[ $GITHUB_EVENT_NAME == 'release' || $GITHUB_REF == refs/tags/* ]]; then
            ./gradlew build -Pbuild.release=true
          else
            ./gradlew build
          fi

      - name: Upload artifacts
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: sodium-artifacts-${{ steps.ref.outputs.ref }}
          path: build/mods/*.jar

      - name: Upload release assets
        if: ${{ github.event_name == 'release' }}
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'build/mods/*.jar'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
